// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brssjzwdfxxhrucuwzpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyc3NqendkZnh4aHJ1Y3V3enByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxODEwNDEsImV4cCI6MjA2MTc1NzA0MX0.t8BK9ZoF3_jZEkKGgDhm8Xv0WI0LjnHaCLz6Qg0kW1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);